// Created by iWeb 3.0.2 local-build-20101111

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id4" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 130px; width: 413px; z-index: 1; "><param name="src" value="Media/1%20soldering%20an%20LED%20level-2.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id4" type="video/quicktime" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 130px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/1%20soldering%20an%20LED%20level.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/1%20soldering%20an%20LED%20level-2.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id4" type="video/quicktime" width="413" height="326" data="Media/1%20soldering%20an%20LED%20level-2.mov" style="height: 326px; left: 143px; position: absolute; top: 130px; width: 413px; z-index: 1; "><param name="src" value="Media/1%20soldering%20an%20LED%20level-2.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id6" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 539px; width: 413px; z-index: 1; "><param name="src" value="Media/2%20level%20layout%20and%20soldering.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id6" type="video/quicktime" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 539px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/2%20level%20layout%20and%20soldering.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/2%20level%20layout%20and%20soldering.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id6" type="video/quicktime" width="413" height="326" data="Media/2%20level%20layout%20and%20soldering.mov" style="height: 326px; left: 143px; position: absolute; top: 539px; width: 413px; z-index: 1; "><param name="src" value="Media/2%20level%20layout%20and%20soldering.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id8" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 948px; width: 413px; z-index: 1; "><param name="src" value="Media/3%20creating%20cube%20frame.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id8" type="video/quicktime" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 948px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/3%20creating%20cube%20frame.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/3%20creating%20cube%20frame.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id8" type="video/quicktime" width="413" height="326" data="Media/3%20creating%20cube%20frame.mov" style="height: 326px; left: 143px; position: absolute; top: 948px; width: 413px; z-index: 1; "><param name="src" value="Media/3%20creating%20cube%20frame.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id10" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 140px; position: absolute; top: 1388px; width: 413px; z-index: 1; "><param name="src" value="Media/4%20planning%20of%20cube%20structure.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id10" type="video/quicktime" width="413" height="326" style="height: 326px; left: 140px; position: absolute; top: 1388px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/4%20planning%20of%20cube%20structure.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/4%20planning%20of%20cube%20structure.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id10" type="video/quicktime" width="413" height="326" data="Media/4%20planning%20of%20cube%20structure.mov" style="height: 326px; left: 140px; position: absolute; top: 1388px; width: 413px; z-index: 1; "><param name="src" value="Media/4%20planning%20of%20cube%20structure.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie5()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id12" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 140px; position: absolute; top: 1830px; width: 413px; z-index: 1; "><param name="src" value="Media/5%20measuring%20and%20marking%20anode%20wire%20holes.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id12" type="video/quicktime" width="413" height="326" style="height: 326px; left: 140px; position: absolute; top: 1830px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/5%20measuring%20and%20marking%20anode%20wire%20holes.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/5%20measuring%20and%20marking%20anode%20wire%20holes.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id12" type="video/quicktime" width="413" height="326" data="Media/5%20measuring%20and%20marking%20anode%20wire%20holes.mov" style="height: 326px; left: 140px; position: absolute; top: 1830px; width: 413px; z-index: 1; "><param name="src" value="Media/5%20measuring%20and%20marking%20anode%20wire%20holes.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie6()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id14" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 2272px; width: 413px; z-index: 1; "><param name="src" value="Media/6%20construction%20of%20base%20part%201.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id14" type="video/quicktime" width="413" height="326" style="height: 326px; left: 143px; position: absolute; top: 2272px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/6%20construction%20of%20base%20part%201.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/6%20construction%20of%20base%20part%201.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id14" type="video/quicktime" width="413" height="326" data="Media/6%20construction%20of%20base%20part%201.mov" style="height: 326px; left: 143px; position: absolute; top: 2272px; width: 413px; z-index: 1; "><param name="src" value="Media/6%20construction%20of%20base%20part%201.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie7()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id16" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 141px; position: absolute; top: 2719px; width: 413px; z-index: 1; "><param name="src" value="Media/6%20construction%20of%20base%20part%202.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id16" type="video/quicktime" width="413" height="326" style="height: 326px; left: 141px; position: absolute; top: 2719px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/6%20construction%20of%20base%20part%202.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/6%20construction%20of%20base%20part%202.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id16" type="video/quicktime" width="413" height="326" data="Media/6%20construction%20of%20base%20part%202.mov" style="height: 326px; left: 141px; position: absolute; top: 2719px; width: 413px; z-index: 1; "><param name="src" value="Media/6%20construction%20of%20base%20part%202.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie8()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id18" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 139px; position: absolute; top: 3182px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%201.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id18" type="video/quicktime" width="413" height="326" style="height: 326px; left: 139px; position: absolute; top: 3182px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/7%20construction%20of%20upper%20body%20part%201.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/7%20construction%20of%20upper%20body%20part%201.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id18" type="video/quicktime" width="413" height="326" data="Media/7%20construction%20of%20upper%20body%20part%201.mov" style="height: 326px; left: 139px; position: absolute; top: 3182px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%201.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie9()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id20" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 133px; position: absolute; top: 3614px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%202.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id20" type="video/quicktime" width="413" height="326" style="height: 326px; left: 133px; position: absolute; top: 3614px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/7%20construction%20of%20upper%20body%20part%202.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/7%20construction%20of%20upper%20body%20part%202.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id20" type="video/quicktime" width="413" height="326" data="Media/7%20construction%20of%20upper%20body%20part%202.mov" style="height: 326px; left: 133px; position: absolute; top: 3614px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%202.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie10()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id22" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 130px; position: absolute; top: 4068px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%203.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id22" type="video/quicktime" width="413" height="326" style="height: 326px; left: 130px; position: absolute; top: 4068px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/7%20construction%20of%20upper%20body%20part%203.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/7%20construction%20of%20upper%20body%20part%203.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id22" type="video/quicktime" width="413" height="326" data="Media/7%20construction%20of%20upper%20body%20part%203.mov" style="height: 326px; left: 130px; position: absolute; top: 4068px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%203.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie11()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id24" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 129px; position: absolute; top: 4522px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%204.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id24" type="video/quicktime" width="413" height="326" style="height: 326px; left: 129px; position: absolute; top: 4522px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/7%20construction%20of%20upper%20body%20part%204.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/7%20construction%20of%20upper%20body%20part%204.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id24" type="video/quicktime" width="413" height="326" data="Media/7%20construction%20of%20upper%20body%20part%204.mov" style="height: 326px; left: 129px; position: absolute; top: 4522px; width: 413px; z-index: 1; "><param name="src" value="Media/7%20construction%20of%20upper%20body%20part%204.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie12()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id26" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 128px; position: absolute; top: 4981px; width: 413px; z-index: 1; "><param name="src" value="Media/8%20addition%20of%20LED%20levels.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id26" type="video/quicktime" width="413" height="326" style="height: 326px; left: 128px; position: absolute; top: 4981px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/8%20addition%20of%20LED%20levels.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/8%20addition%20of%20LED%20levels.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id26" type="video/quicktime" width="413" height="326" data="Media/8%20addition%20of%20LED%20levels.mov" style="height: 326px; left: 128px; position: absolute; top: 4981px; width: 413px; z-index: 1; "><param name="src" value="Media/8%20addition%20of%20LED%20levels.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie13()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id28" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 127px; position: absolute; top: 5427px; width: 413px; z-index: 1; "><param name="src" value="Media/9%20soldering%20LED%20levlels%20to%20frame.mov" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id28" type="video/quicktime" width="413" height="326" style="height: 326px; left: 127px; position: absolute; top: 5427px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/9%20soldering%20LED%20levlels%20to%20frame.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/9%20soldering%20LED%20levlels%20to%20frame.mov"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id28" type="video/quicktime" width="413" height="326" data="Media/9%20soldering%20LED%20levlels%20to%20frame.mov" style="height: 326px; left: 127px; position: absolute; top: 5427px; width: 413px; z-index: 1; "><param name="src" value="Media/9%20soldering%20LED%20levlels%20to%20frame.mov"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie14()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id30" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="413" height="326" style="height: 326px; left: 126px; position: absolute; top: 5873px; width: 413px; z-index: 1; "><param name="src" value="Media/led%20cube%20testing.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id30" type="video/quicktime" width="413" height="326" style="height: 326px; left: 126px; position: absolute; top: 5873px; width: 413px; z-index: 1; "><param name="src" value="Videos_files/led%20cube%20testing.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/led%20cube%20testing.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id30" type="video/quicktime" width="413" height="326" data="Media/led%20cube%20testing.m4v" style="height: 326px; left: 126px; position: absolute; top: 5873px; width: 413px; z-index: 1; "><param name="src" value="Media/led%20cube%20testing.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Videos_files/VideosMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id15');adjustFontSizeIfTooBig('id15');adjustLineHeightIfTooBig('id17');adjustFontSizeIfTooBig('id17');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id21');adjustFontSizeIfTooBig('id21');adjustLineHeightIfTooBig('id23');adjustFontSizeIfTooBig('id23');adjustLineHeightIfTooBig('id25');adjustFontSizeIfTooBig('id25');adjustLineHeightIfTooBig('id27');adjustFontSizeIfTooBig('id27');adjustLineHeightIfTooBig('id29');adjustFontSizeIfTooBig('id29');adjustLineHeightIfTooBig('id31');adjustFontSizeIfTooBig('id31');fixAllIEPNGs('Media/transparent.gif');performPostEffectsFixups()}
