// Created by iWeb 3.0.2 local-build-20101209

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id3" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 197px; width: 600px; z-index: 1; "><param name="src" value="Media/Letter%20%27I%27.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id3" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 197px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/Letter%20%27I%27.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/Letter%20%27I%27.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id3" type="video/quicktime" width="600" height="466" data="Media/Letter%20%27I%27.mp4" style="height: 466px; left: 50px; position: absolute; top: 197px; width: 600px; z-index: 1; "><param name="src" value="Media/Letter%20%27I%27.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id7" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 903px; width: 600px; z-index: 1; "><param name="src" value="Media/Letter%20%27X%27.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id7" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 903px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/Letter%20%27X%27.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/Letter%20%27X%27.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id7" type="video/quicktime" width="600" height="466" data="Media/Letter%20%27X%27.mp4" style="height: 466px; left: 50px; position: absolute; top: 903px; width: 600px; z-index: 1; "><param name="src" value="Media/Letter%20%27X%27.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id9" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 1608px; width: 600px; z-index: 1; "><param name="src" value="Media/Pulse%20through%20Wnding%20Coil.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id9" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 1608px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/Pulse%20through%20Wnding%20Coil.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/Pulse%20through%20Wnding%20Coil.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id9" type="video/quicktime" width="600" height="466" data="Media/Pulse%20through%20Wnding%20Coil.mp4" style="height: 466px; left: 50px; position: absolute; top: 1608px; width: 600px; z-index: 1; "><param name="src" value="Media/Pulse%20through%20Wnding%20Coil.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id11" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 2313px; width: 600px; z-index: 1; "><param name="src" value="Media/LED%20Wave.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id11" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 2313px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/LED%20Wave.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/LED%20Wave.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id11" type="video/quicktime" width="600" height="466" data="Media/LED%20Wave.mp4" style="height: 466px; left: 50px; position: absolute; top: 2313px; width: 600px; z-index: 1; "><param name="src" value="Media/LED%20Wave.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie5()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id13" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="588" height="497" style="height: 497px; left: 56px; position: absolute; top: 3031px; width: 588px; z-index: 1; "><param name="src" value="Media/ISU%20-%20Mirrored%20LEDs%20-%202.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id13" type="video/quicktime" width="588" height="497" style="height: 497px; left: 56px; position: absolute; top: 3031px; width: 588px; z-index: 1; "><param name="src" value="Videos_files/ISU%20-%20Mirrored%20LEDs%20-%202.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/ISU%20-%20Mirrored%20LEDs%20-%202.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id13" type="video/quicktime" width="588" height="497" data="Media/ISU%20-%20Mirrored%20LEDs%20-%202.mp4" style="height: 497px; left: 56px; position: absolute; top: 3031px; width: 588px; z-index: 1; "><param name="src" value="Media/ISU%20-%20Mirrored%20LEDs%20-%202.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie6()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id15" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 3723px; width: 600px; z-index: 1; "><param name="src" value="Media/LDR%20-%20Gradual%20Display.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id15" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 3723px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/LDR%20-%20Gradual%20Display.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/LDR%20-%20Gradual%20Display.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id15" type="video/quicktime" width="600" height="466" data="Media/LDR%20-%20Gradual%20Display.mp4" style="height: 466px; left: 50px; position: absolute; top: 3723px; width: 600px; z-index: 1; "><param name="src" value="Media/LDR%20-%20Gradual%20Display.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie7()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id17" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 4428px; width: 600px; z-index: 1; "><param name="src" value="Media/LDR%20-%20Circuit%20Switch.mp4" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id17" type="video/quicktime" width="600" height="466" style="height: 466px; left: 50px; position: absolute; top: 4428px; width: 600px; z-index: 1; "><param name="src" value="Videos_files/LDR%20-%20Circuit%20Switch.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/LDR%20-%20Circuit%20Switch.mp4"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id17" type="video/quicktime" width="600" height="466" data="Media/LDR%20-%20Circuit%20Switch.mp4" style="height: 466px; left: 50px; position: absolute; top: 4428px; width: 600px; z-index: 1; "><param name="src" value="Media/LDR%20-%20Circuit%20Switch.mp4"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Videos_files/VideosMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id14');adjustFontSizeIfTooBig('id14');adjustLineHeightIfTooBig('id16');adjustFontSizeIfTooBig('id16');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');fixAllIEPNGs('Media/transparent.gif');performPostEffectsFixups()}
