// Created by iWeb 3.0.2 local-build-20110121

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,86),url:'Conclusion_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Conclusion_files/stroke_17.png'},{rect:new IWRect(1,-1,659,2),url:'Conclusion_files/stroke_18.png'},{rect:new IWRect(660,-1,2,2),url:'Conclusion_files/stroke_19.png'},{rect:new IWRect(660,1,2,86),url:'Conclusion_files/stroke_20.png'},{rect:new IWRect(660,87,2,2),url:'Conclusion_files/stroke_21.png'},{rect:new IWRect(1,87,659,2),url:'Conclusion_files/stroke_22.png'},{rect:new IWRect(-1,87,2,2),url:'Conclusion_files/stroke_23.png'}],new IWSize(661,88)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,219),url:'Conclusion_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Conclusion_files/stroke_1.png'},{rect:new IWRect(1,-1,156,2),url:'Conclusion_files/stroke_2.png'},{rect:new IWRect(157,-1,3,2),url:'Conclusion_files/stroke_3.png'},{rect:new IWRect(157,1,3,219),url:'Conclusion_files/stroke_4.png'},{rect:new IWRect(157,220,3,2),url:'Conclusion_files/stroke_5.png'},{rect:new IWRect(1,220,156,2),url:'Conclusion_files/stroke_6.png'},{rect:new IWRect(-1,220,2,2),url:'Conclusion_files/stroke_7.png'}],new IWSize(158,221)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,220),url:'Conclusion_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Conclusion_files/stroke_9.png'},{rect:new IWRect(1,-1,165,2),url:'Conclusion_files/stroke_10.png'},{rect:new IWRect(166,-1,2,2),url:'Conclusion_files/stroke_11.png'},{rect:new IWRect(166,1,2,220),url:'Conclusion_files/stroke_12.png'},{rect:new IWRect(166,221,2,3),url:'Conclusion_files/stroke_13.png'},{rect:new IWRect(1,221,165,3),url:'Conclusion_files/stroke_14.png'},{rect:new IWRect(-1,221,2,3),url:'Conclusion_files/stroke_15.png'}],new IWSize(167,223))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Conclusion_files/ConclusionMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
