// Created by iWeb 3.0.2 local-build-20110121

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-2,2,4,382),url:'Schematics_files/stroke.png'},{rect:new IWRect(-2,-2,4,4),url:'Schematics_files/stroke_1.png'},{rect:new IWRect(2,-2,523,4),url:'Schematics_files/stroke_2.png'},{rect:new IWRect(525,-2,4,4),url:'Schematics_files/stroke_3.png'},{rect:new IWRect(525,2,4,382),url:'Schematics_files/stroke_4.png'},{rect:new IWRect(525,384,4,5),url:'Schematics_files/stroke_5.png'},{rect:new IWRect(2,384,523,5),url:'Schematics_files/stroke_6.png'},{rect:new IWRect(-2,384,4,5),url:'Schematics_files/stroke_7.png'}],new IWSize(527,386)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,86),url:'Schematics_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Schematics_files/stroke_9.png'},{rect:new IWRect(1,-1,659,2),url:'Schematics_files/stroke_10.png'},{rect:new IWRect(660,-1,2,2),url:'Schematics_files/stroke_11.png'},{rect:new IWRect(660,1,2,86),url:'Schematics_files/stroke_12.png'},{rect:new IWRect(660,87,2,2),url:'Schematics_files/stroke_13.png'},{rect:new IWRect(1,87,659,2),url:'Schematics_files/stroke_14.png'},{rect:new IWRect(-1,87,2,2),url:'Schematics_files/stroke_15.png'}],new IWSize(661,88))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Schematics_files/SchematicsMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
