// Created by iWeb 3.0.2 local-build-20110121

setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_2:new IWStrokeParts([{rect:new IWRect(-1,1,2,86),url:'Program_Code_files/stroke_16.png'},{rect:new IWRect(-1,-1,2,2),url:'Program_Code_files/stroke_17.png'},{rect:new IWRect(1,-1,659,2),url:'Program_Code_files/stroke_18.png'},{rect:new IWRect(660,-1,2,2),url:'Program_Code_files/stroke_19.png'},{rect:new IWRect(660,1,2,86),url:'Program_Code_files/stroke_20.png'},{rect:new IWRect(660,87,2,2),url:'Program_Code_files/stroke_21.png'},{rect:new IWRect(1,87,659,2),url:'Program_Code_files/stroke_22.png'},{rect:new IWRect(-1,87,2,2),url:'Program_Code_files/stroke_23.png'}],new IWSize(661,88)),stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,824),url:'Program_Code_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Program_Code_files/stroke_1.png'},{rect:new IWRect(1,-1,632,2),url:'Program_Code_files/stroke_2.png'},{rect:new IWRect(633,-1,2,2),url:'Program_Code_files/stroke_3.png'},{rect:new IWRect(633,1,2,824),url:'Program_Code_files/stroke_4.png'},{rect:new IWRect(633,825,2,2),url:'Program_Code_files/stroke_5.png'},{rect:new IWRect(1,825,632,2),url:'Program_Code_files/stroke_6.png'},{rect:new IWRect(-1,825,2,2),url:'Program_Code_files/stroke_7.png'}],new IWSize(634,826)),stroke_3:new IWStrokeParts([{rect:new IWRect(-1,1,2,587),url:'Program_Code_files/stroke_24.png'},{rect:new IWRect(-1,-1,2,2),url:'Program_Code_files/stroke_25.png'},{rect:new IWRect(1,-1,553,2),url:'Program_Code_files/stroke_26.png'},{rect:new IWRect(554,-1,2,2),url:'Program_Code_files/stroke_27.png'},{rect:new IWRect(554,1,2,587),url:'Program_Code_files/stroke_28.png'},{rect:new IWRect(554,588,2,2),url:'Program_Code_files/stroke_29.png'},{rect:new IWRect(1,588,553,2),url:'Program_Code_files/stroke_30.png'},{rect:new IWRect(-1,588,2,2),url:'Program_Code_files/stroke_31.png'}],new IWSize(555,589)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,1284),url:'Program_Code_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Program_Code_files/stroke_9.png'},{rect:new IWRect(1,-1,629,2),url:'Program_Code_files/stroke_10.png'},{rect:new IWRect(630,-1,2,2),url:'Program_Code_files/stroke_11.png'},{rect:new IWRect(630,1,2,1284),url:'Program_Code_files/stroke_12.png'},{rect:new IWRect(630,1285,2,2),url:'Program_Code_files/stroke_13.png'},{rect:new IWRect(1,1285,629,2),url:'Program_Code_files/stroke_14.png'},{rect:new IWRect(-1,1285,2,2),url:'Program_Code_files/stroke_15.png'}],new IWSize(631,1286))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Program_Code_files/Program_CodeMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
