// Created by iWeb 3.0.2 local-build-20110121

function writeMovie1()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id14" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="441" height="264" style="height: 264px; left: 132px; position: absolute; top: 3508px; width: 441px; z-index: 1; "><param name="src" value="Media/Y.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id14" type="video/quicktime" width="441" height="264" style="height: 264px; left: 132px; position: absolute; top: 3508px; width: 441px; z-index: 1; "><param name="src" value="Multimedia_files/Y.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/Y.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id14" type="video/quicktime" width="441" height="264" data="Media/Y.m4v" style="height: 264px; left: 132px; position: absolute; top: 3508px; width: 441px; z-index: 1; "><param name="src" value="Media/Y.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie2()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id15" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="459" height="274" style="height: 274px; left: 127px; position: absolute; top: 3959px; width: 459px; z-index: 1; "><param name="src" value="Media/X%26Y.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id15" type="video/quicktime" width="459" height="274" style="height: 274px; left: 127px; position: absolute; top: 3959px; width: 459px; z-index: 1; "><param name="src" value="Multimedia_files/X%26Y.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/X%26Y.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id15" type="video/quicktime" width="459" height="274" data="Media/X%26Y.m4v" style="height: 274px; left: 127px; position: absolute; top: 3959px; width: 459px; z-index: 1; "><param name="src" value="Media/X%26Y.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie3()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id16" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="425" height="255" style="height: 255px; left: 134px; position: absolute; top: 3074px; width: 425px; z-index: 1; "><param name="src" value="Media/C1.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id16" type="video/quicktime" width="425" height="255" style="height: 255px; left: 134px; position: absolute; top: 3074px; width: 425px; z-index: 1; "><param name="src" value="Multimedia_files/C1.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/C1.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id16" type="video/quicktime" width="425" height="255" data="Media/C1.m4v" style="height: 255px; left: 134px; position: absolute; top: 3074px; width: 425px; z-index: 1; "><param name="src" value="Media/C1.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
function writeMovie4()
{detectBrowser();if(windowsInternetExplorer)
{document.write('<object id="id17" classid="clsid:02BF25D5-8C17-4B23-BC80-D3488ABDDC6B" codebase="http://www.apple.com/qtactivex/qtplugin.cab" width="416" height="250" style="height: 250px; left: 136px; position: absolute; top: 2668px; width: 416px; z-index: 1; "><param name="src" value="Media/C2.m4v" /><param name="controller" value="true" /><param name="autoplay" value="false" /><param name="scale" value="tofit" /><param name="volume" value="100" /><param name="loop" value="false" /></object>');}
else if(isiPhone)
{document.write('<object id="id17" type="video/quicktime" width="416" height="250" style="height: 250px; left: 136px; position: absolute; top: 2668px; width: 416px; z-index: 1; "><param name="src" value="Multimedia_files/C2.jpg"/><param name="target" value="myself"/><param name="href" value="../Media/C2.m4v"/><param name="controller" value="true"/><param name="scale" value="tofit"/></object>');}
else
{document.write('<object id="id17" type="video/quicktime" width="416" height="250" data="Media/C2.m4v" style="height: 250px; left: 136px; position: absolute; top: 2668px; width: 416px; z-index: 1; "><param name="src" value="Media/C2.m4v"/><param name="controller" value="true"/><param name="autoplay" value="false"/><param name="scale" value="tofit"/><param name="volume" value="100"/><param name="loop" value="false"/></object>');}}
setTransparentGifURL('Media/transparent.gif');function applyEffects()
{var registry=IWCreateEffectRegistry();registry.registerEffects({stroke_0:new IWStrokeParts([{rect:new IWRect(-1,1,2,120),url:'Multimedia_files/stroke.png'},{rect:new IWRect(-1,-1,2,2),url:'Multimedia_files/stroke_1.png'},{rect:new IWRect(1,-1,77,2),url:'Multimedia_files/stroke_2.png'},{rect:new IWRect(78,-1,2,2),url:'Multimedia_files/stroke_3.png'},{rect:new IWRect(78,1,2,120),url:'Multimedia_files/stroke_4.png'},{rect:new IWRect(78,121,2,2),url:'Multimedia_files/stroke_5.png'},{rect:new IWRect(1,121,77,2),url:'Multimedia_files/stroke_6.png'},{rect:new IWRect(-1,121,2,2),url:'Multimedia_files/stroke_7.png'}],new IWSize(79,122)),stroke_1:new IWStrokeParts([{rect:new IWRect(-1,1,2,86),url:'Multimedia_files/stroke_8.png'},{rect:new IWRect(-1,-1,2,2),url:'Multimedia_files/stroke_9.png'},{rect:new IWRect(1,-1,659,2),url:'Multimedia_files/stroke_10.png'},{rect:new IWRect(660,-1,2,2),url:'Multimedia_files/stroke_11.png'},{rect:new IWRect(660,1,2,86),url:'Multimedia_files/stroke_12.png'},{rect:new IWRect(660,87,2,2),url:'Multimedia_files/stroke_13.png'},{rect:new IWRect(1,87,659,2),url:'Multimedia_files/stroke_14.png'},{rect:new IWRect(-1,87,2,2),url:'Multimedia_files/stroke_15.png'}],new IWSize(661,88))});registry.applyEffects();}
function hostedOnDM()
{return false;}
function onPageLoad()
{loadMozillaCSS('Multimedia_files/MultimediaMoz.css')
adjustLineHeightIfTooBig('id1');adjustFontSizeIfTooBig('id1');adjustLineHeightIfTooBig('id2');adjustFontSizeIfTooBig('id2');adjustLineHeightIfTooBig('id3');adjustFontSizeIfTooBig('id3');adjustLineHeightIfTooBig('id4');adjustFontSizeIfTooBig('id4');adjustLineHeightIfTooBig('id5');adjustFontSizeIfTooBig('id5');adjustLineHeightIfTooBig('id6');adjustFontSizeIfTooBig('id6');adjustLineHeightIfTooBig('id7');adjustFontSizeIfTooBig('id7');adjustLineHeightIfTooBig('id8');adjustFontSizeIfTooBig('id8');adjustLineHeightIfTooBig('id9');adjustFontSizeIfTooBig('id9');adjustLineHeightIfTooBig('id10');adjustFontSizeIfTooBig('id10');adjustLineHeightIfTooBig('id11');adjustFontSizeIfTooBig('id11');adjustLineHeightIfTooBig('id12');adjustFontSizeIfTooBig('id12');adjustLineHeightIfTooBig('id13');adjustFontSizeIfTooBig('id13');adjustLineHeightIfTooBig('id18');adjustFontSizeIfTooBig('id18');adjustLineHeightIfTooBig('id19');adjustFontSizeIfTooBig('id19');adjustLineHeightIfTooBig('id20');adjustFontSizeIfTooBig('id20');fixAllIEPNGs('Media/transparent.gif');applyEffects()}
